# Generated by Django 5.2.7 on 2025-11-28 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('beginning_message_id', models.UUIDField(blank=True, null=True)),
                ('ending_message_id', models.UUIDField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('message_count', models.IntegerField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversation_files',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('participant_type', models.CharField(choices=[('human', 'Human'), ('ai', 'AI'), ('tool', 'Tool'), ('oracle', 'Oracle'), ('system', 'System')], default='human', max_length=20)),
            ],
            options={
                'db_table': 'conversation_participants',
            },
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'eras',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('message_number', models.IntegerField(blank=True, null=True)),
                ('content', models.JSONField()),
                ('looking_for_parent_id', models.UUIDField(blank=True, help_text='UUID of parent that was not found during import', null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('eth_blockheight', models.BigIntegerField(blank=True, null=True)),
                ('eth_block_offset', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_backend', models.CharField(blank=True, max_length=100, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('missing_from_markdown', models.BooleanField(default=False)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('cache_creation_input_tokens', models.IntegerField(blank=True, null=True)),
                ('cache_read_input_tokens', models.IntegerField(blank=True, null=True)),
                ('is_sidechain', models.BooleanField(default=False)),
                ('is_synthetic_error', models.BooleanField(default=False)),
                ('is_retry', models.BooleanField(default=False)),
                ('is_continuation_message', models.BooleanField(default=False)),
                ('apparent_duplicate', models.BooleanField(default=False, help_text='True if this message was encountered again during import with different content (likely whitespace differences)')),
                ('cwd', models.TextField(blank=True, null=True)),
                ('git_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('client_version', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(default='misc', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThinkingEntity',
            fields=[
                ('conversationparticipant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conversations.conversationparticipant')),
                ('is_biological_human', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'thinking entities',
                'db_table': 'thinking_entities',
            },
            bases=('conversations.conversationparticipant',),
        ),
        migrations.CreateModel(
            name='ContextHeap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('fresh', 'Fresh conversation'), ('post_compacting', 'After compacting'), ('split_point', 'Context split')], default='fresh', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_heaps', to='conversations.era')),
            ],
            options={
                'db_table': 'context_heaps',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conversations.message')),
                ('signature', models.TextField()),
            ],
            bases=('conversations.message',),
        ),
        migrations.CreateModel(
            name='ToolResult',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conversations.message')),
                ('tool_use_id', models.CharField(db_index=True, max_length=100)),
                ('is_error', models.BooleanField(default=False)),
            ],
            bases=('conversations.message',),
        ),
        migrations.CreateModel(
            name='ToolUse',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conversations.message')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_id', models.CharField(max_length=100)),
            ],
            bases=('conversations.message',),
        ),
        migrations.AddField(
            model_name='message',
            name='context_heap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.contextheap'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='conversations.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', to='conversations.conversationparticipant'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='conversations.conversationparticipant'),
        ),
        migrations.CreateModel(
            name='CompactingAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('looking_for_ending_message', models.UUIDField(blank=True, help_text='UUID of ending message that was not found during import', null=True)),
                ('compact_trigger', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_compact_tokens', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_heap', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compacting_action', to='conversations.contextheap')),
                ('continuation_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuation_for_compacting_action', to='conversations.message')),
                ('ending_message', models.OneToOneField(blank=True, db_column='ending_message_fk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compacting_action_ending_here', to='conversations.message')),
            ],
            options={
                'db_table': 'compacting_actions',
            },
        ),
        migrations.CreateModel(
            name='RawImportedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('raw_data', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_imports', to='conversations.conversationfile')),
            ],
            options={
                'db_table': 'raw_imported_content',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_text', models.TextField()),
                ('looking_for_leaf_message', models.UUIDField(blank=True, help_text='UUID of the leaf message that was not found during import (from leafUuid)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leaf_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries_ending_here', to='conversations.message')),
            ],
            options={
                'verbose_name_plural': 'summaries',
                'db_table': 'summaries',
            },
        ),
        migrations.CreateModel(
            name='MessageTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField()),
                ('relevance', models.IntegerField(default=5, help_text='1-10 scale')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.topic')),
            ],
            options={
                'db_table': 'message_topics',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('content', models.TextField()),
                ('eth_blockheight', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_notes', to='conversations.thinkingentity')),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session_id', 'timestamp'], name='conversatio_session_2f9f92_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='conversatio_sender__ed16aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('context_heap', 'message_number')},
        ),
        migrations.AddIndex(
            model_name='rawimportedcontent',
            index=models.Index(fields=['content_type', 'object_id'], name='raw_importe_content_fae991_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagetopic',
            unique_together={('message_id', 'topic')},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['content_type', 'object_id'], name='notes_content_0b9624_idx'),
        ),
    ]
